/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  pwm                                    */
/*      FILE         :  pwm.c                                  */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <iodefine.h>
#include "pwm.h"

#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

int main(void) {
	main_clock_initialize();
	pwm_initialize();
    while(1) {

	// TODO: add application code here
    }
return 0;
}
void main_clock_initialize(void) {

	//PLL(Phase Locked Loop:発振器からの周波数を逓倍)の動作周波数はMAX:200MHz
	//動作周期は100MHz
	/* PLL回路 20逓倍× 入力1分周 (10.000MHz * 20 = 200MHz)
	 * 0b00 010011 000000 00 = 0x1300*/
	SYSTEM.PRCR.WORD = 0xa501; /*クロックソース選択の保護の解除*/
	SYSTEM.PLLCR.WORD = 0x1300;
	SYSTEM.PLLCR2.BIT.PLLEN = 0; /*PLL ENABLE */

	/* BCLK端子出力1/4(MAX:50MHz)(BCLKとBCLK端子出力は別)0010b
	 * PCLKB1/4(MAX:50MHz)0010b
	 * PCLKA=ICLK1/2(MAX:100MHz)0001b
	 * SDCLK停止 1
	 * BCLK停止 1
	 * ICK1/2(MAX:100MHz) 0001b
	 * FCK1/4(MAX:50MHz) 0010b
	 * 0b 0010 0001 1 1 00 0001 0010 0010 0001 0001 = 0x21C12211 */
	SYSTEM.SCKCR.LONG = 0x21C12211;

	/* IEBCK1/4(MAX:50MHz)0010b
	 * UCLK1/4(使わない場合0001b)
	 * 00000000 0001 0010b = 0x0012  */
	SYSTEM.SCKCR2.WORD = 0x0012;

	/*BCLK = (1/2) * PLL(MAX:100MHz) */
	SYSTEM.BCKCR.BYTE = 0x01;

	/* クロックソース選択：PLL回路選択100
	 * 00000 100 00000000b = 0x0400*/
	SYSTEM.SCKCR3.WORD = 0x0400;

	SYSTEM.PRCR.WORD = 0xa500; /*クロックソース選択の保護*/
}
void pwm_initialize(void) {
	int period = 500;               //分解能を500に設定
	int duty = 450;
	// MTU3
	SYSTEM.PRCR.WORD = 0xa50b;      // Release Protect
	MSTP(MTU3) = 0;                 // Wake up MTU3
	SYSTEM.PRCR.WORD = 0xa500;      // Protect

	// Set MPC
	PORT1.PMR.BIT.B4 = 1;           // Set P14: Peripheral

	MPC.PWPR.BIT.B0WI = 0;          // protect
	MPC.PWPR.BIT.PFSWE = 1;         // Release Protect

	MPC.P14PFS.BIT.PSEL = 1;        // Set P14: MTIOC3A

	MPC.PWPR.BIT.PFSWE = 0;         // Protect
	MPC.PWPR.BIT.B0WI = 1;          // Release Protect

	// PWM Settings
	MTU3.TCR.BIT.TPSC = 0;          // PCLK/1 = 50MHz/1 = 50MHz
	MTU3.TCR.BIT.CKEG = 0;          // Count rising edge
	MTU3.TCR.BIT.CCLR = 1;          // TGRAのコンペアマッチでMTU3のカウントをリセット

	MTU3.TMDR.BIT.MD = 2;           // MTU3 PWMモード1

	MTU3.TIORH.BIT.IOA = 1;         // Compare Output High
	MTU3.TIORH.BIT.IOB = 3;         // Compare Output Low

	MTU3.TGRA = period - 1;             // 1kHz(65535)
	MTU3.TGRB = 1;                      // Duty 0%

	MTU3.TCNT = 0;                      // Clear MTU3 count
	MTU.TSTR.BIT.CST3 = 1;              // Start MTU3 count

	MTU3.TGRB = duty;
}
