/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  cmt                                    */
/*      FILE         :  cmt.c                                  */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <iodefine.h>
#include "cmt.h"
#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

int main(void) {
	PORT1.PDR.BIT.B4 = 1;
	main_clock_initialize();
	CMT0_initialize();
    while(1) {

	// TODO: add application code here
    }
return 0;
}
void main_clock_initialize(void) {

	//PLL(Phase Locked Loop:発振器からの周波数を逓倍)の動作周波数はMAX:200MHz
	//動作周期は100MHz
	/* PLL回路 20逓倍× 入力1分周 (10.000MHz * 20 = 200MHz)
	 * 0b00 010011 000000 00 = 0x1300*/
	SYSTEM.PRCR.WORD = 0xa501; /*クロックソース選択の保護の解除*/
	SYSTEM.PLLCR.WORD = 0x1300;
	SYSTEM.PLLCR2.BIT.PLLEN = 0; /*PLL ENABLE */

	/* BCLK端子出力1/4(MAX:50MHz)(BCLKとBCLK端子出力は別)0010b
	 * PCLKB1/4(MAX:50MHz)0010b
	 * PCLKA=ICLK1/2(MAX:100MHz)0001b
	 * SDCLK停止 1
	 * BCLK停止 1
	 * ICK1/2(MAX:100MHz) 0001b
	 * FCK1/4(MAX:50MHz) 0010b
	 * 0b 0010 0001 1 1 00 0001 0010 0010 0001 0001 = 0x21C12211 */
	SYSTEM.SCKCR.LONG = 0x21C12211;

	/* IEBCK1/4(MAX:50MHz)0010b
	 * UCLK1/4(使わない場合0001b)
	 * 00000000 0001 0010b = 0x0012  */
	SYSTEM.SCKCR2.WORD = 0x0012;

	/*BCLK = (1/2) * PLL(MAX:100MHz) */
	SYSTEM.BCKCR.BYTE = 0x01;

	/* クロックソース選択：PLL回路選択100
	 * 00000 100 00000000b = 0x0400*/
	SYSTEM.SCKCR3.WORD = 0x0400;

	SYSTEM.PRCR.WORD = 0xa500; /*クロックソース選択の保護*/
}

void CMT0_initialize(void) {
	SYSTEM.PRCR.WORD = 0xa50b; /*クロックソース選択の保護の解除*/
	MSTP(CMT0) = 0;             // Wake up CMT0//CMT0の運用開始
	SYSTEM.PRCR.WORD = 0xa500;/*クロックソース選択の保護*/

	CMT.CMSTR0.BIT.STR0 = 0;    // Disable CMT0 count
	CMT0.CMCR.BIT.CMIE = 0;  //CMI0(コンペアマッチ割り込み)禁止

	CMT0.CMCR.BIT.CKS = 3; //8分周
	CMT0.CMCNT = 0;                         //カウンタのリセット
	CMT0.CMCOR = (int) (6250000 / 64 / 2) - 1; //カウントが4999で割り込み 50MHz/8/625 = 10kHz すなはち 100us周期の割り込み

	CMT0.CMCR.BIT.CMIE = 1;                         //CMI0(コンペアマッチ割り込み)許可
	CMT.CMSTR0.BIT.STR0 = 1;    // Enable CMT0 count

	IEN(CMT0,CMI0)= 1;                     //割り込みを許可する
	IPR(CMT0,CMI0)= 6;                     //CMI0の割り込み優先度6を設定(MAX15,MIN1)
}
